### ISSUE TITLE
Dashboard bar chart error

### ISSUE THREAD

**Issue by ItIsGreg** [trostalski/whipple#4]
After uploading a dataset I want to create a dashboard card. I selected BarChart as the chart type. After creating the chart the page went blank. The console log of chromes dev tools shows:

Uncaught Error: "category" is not a registered scale.
    at Registry._get (core.registry.js:178:1)
    at Registry.getScale (core.registry.js:90:1)
    at core.controller.js:370:1
    at each (helpers.core.ts:149:1)
    at Chart.buildOrUpdateScales (core.controller.js:355:1)
    at Chart._updateScales (core.controller.js:561:1)
    at Chart.update (core.controller.js:495:1)
    at new Chart (core.controller.js:206:1)
    at renderChart (chart.tsx:41:1)
    at chart.tsx:97:1
react-dom.development.js:18687 The above error occurred in the <ForwardRef(ChartComponent)> component:

    at ChartComponent (http://localhost:3000/static/js/bundle.js:325063:5)
    at div
    at DashboardBarChart (http://localhost:3000/static/js/bundle.js:1427:81)
    at div
    at div
    at DashboardCard (http://localhost:3000/static/js/bundle.js:1737:80)
    at div
    at div
    at div
    at Wrapper (http://localhost:3000/static/js/bundle.js:725:5)
    at Dashboard (http://localhost:3000/static/js/bundle.js:5011:94)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:203607:5)
    at Routes (http://localhost:3000/static/js/bundle.js:204050:5)
    at div
    at Router (http://localhost:3000/static/js/bundle.js:203988:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:202306:5)
    at QueryClientProvider (http://localhost:3000/static/js/bundle.js:200728:21)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
react-dom.development.js:12056 Uncaught Error: "category" is not a registered scale.
    at Registry._get (core.registry.js:178:1)
    at Registry.getScale (core.registry.js:90:1)
    at core.controller.js:370:1
    at each (helpers.core.ts:149:1)
    at Chart.buildOrUpdateScales (core.controller.js:355:1)
    at Chart._updateScales (core.controller.js:561:1)
    at Chart.update (core.controller.js:495:1)
    at new Chart (core.controller.js:206:1)
    at renderChart (chart.tsx:41:1)
    at chart.tsx:97:1

**Comment by trostalski** [comment]
@ItIsGreg should be fixed now.
